import type { CorpCodeEntry } from "./types";
import {
  isChosungOnly,
  matchChosung,
  resolveAbbreviation,
  levenshtein,
} from "./korean-search";

interface CorpCodeCache {
  entries: CorpCodeEntry[];
  byCorpCode: Map<string, CorpCodeEntry>;
  byStockCode: Map<string, CorpCodeEntry>;
}

let cache: CorpCodeCache | null = null;

function initCache(): CorpCodeCache {
  if (cache) return cache;

  // Dynamic import of static JSON data (generated by scripts/update-corp-codes.ts)
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const corpCodesData = require("@/data/corp-codes.json") as CorpCodeEntry[];

  const byCorpCode = new Map<string, CorpCodeEntry>();
  const byStockCode = new Map<string, CorpCodeEntry>();

  // Codes are fixed-width identifiers, not numbers. Restore any leading zeros
  // lost upstream so a stale data file still resolves "005930" instead of
  // silently answering "no such company".
  for (const entry of corpCodesData) {
    entry.corp_code = String(entry.corp_code ?? "").padStart(8, "0");
    entry.stock_code = entry.stock_code
      ? String(entry.stock_code).padStart(6, "0")
      : "";

    byCorpCode.set(entry.corp_code, entry);
    if (entry.stock_code) {
      byStockCode.set(entry.stock_code, entry);
    }
  }

  cache = { entries: corpCodesData, byCorpCode, byStockCode };
  return cache;
}

export async function searchCompanies(
  query: string,
  _apiKey?: string,
  limit: number = 10
): Promise<CorpCodeEntry[]> {
  const c = initCache();
  const q = query.trim();

  if (!q) return [];

  // 1. Exact stock code match (6-digit). Also accept a zero-stripped code —
  // users copy "5930" out of tools that treated it as a number.
  const byStock =
    c.byStockCode.get(q) ??
    (/^\d{1,6}$/.test(q) ? c.byStockCode.get(q.padStart(6, "0")) : undefined);
  if (byStock) return [byStock];

  // 2. Exact corp code match (8-digit), same tolerance
  const byCode =
    c.byCorpCode.get(q) ??
    (/^\d{1,8}$/.test(q) ? c.byCorpCode.get(q.padStart(8, "0")) : undefined);
  if (byCode) return [byCode];

  // 3. Abbreviation match (삼전 → 삼성전자)
  const abbrNames = resolveAbbreviation(q);
  if (abbrNames.length > 0) {
    const abbrResults: CorpCodeEntry[] = [];
    for (const entry of c.entries) {
      for (const abbrName of abbrNames) {
        if (entry.corp_name === abbrName || entry.corp_name.includes(abbrName)) {
          abbrResults.push(entry);
        }
      }
      if (abbrResults.length >= limit) break;
    }
    if (abbrResults.length > 0) return sortByListed(abbrResults).slice(0, limit);
  }

  // 4. Chosung search (ㅎㄷㅈㄷㅊ → 현대자동차)
  if (isChosungOnly(q)) {
    const chosungResults: CorpCodeEntry[] = [];
    for (const entry of c.entries) {
      if (matchChosung(entry.corp_name, q)) {
        chosungResults.push(entry);
      }
      if (chosungResults.length >= limit * 3) break;
    }
    return sortByListed(chosungResults).slice(0, limit);
  }

  // 5. Standard text search: exact > prefix > contains
  const qLower = q.toLowerCase().replace(/\s/g, "");
  const exactMatches: CorpCodeEntry[] = [];
  const prefixMatches: CorpCodeEntry[] = [];
  const containsMatches: CorpCodeEntry[] = [];

  for (const entry of c.entries) {
    const name = entry.corp_name.toLowerCase().replace(/\s/g, "");
    if (name === qLower) {
      exactMatches.push(entry);
    } else if (name.startsWith(qLower)) {
      prefixMatches.push(entry);
    } else if (name.includes(qLower)) {
      containsMatches.push(entry);
    }

    if (exactMatches.length + prefixMatches.length + containsMatches.length >= limit * 3) {
      break;
    }
  }

  const textResults = [...exactMatches, ...prefixMatches, ...containsMatches];
  if (textResults.length > 0) {
    return sortByListed(textResults).slice(0, limit);
  }

  // 6. Levenshtein distance fallback (typo tolerance, only for listed companies)
  if (q.length >= 2) {
    const fuzzyResults: Array<{ entry: CorpCodeEntry; dist: number }> = [];
    for (const entry of c.entries) {
      if (!entry.stock_code) continue; // Only listed companies for fuzzy
      const dist = levenshtein(
        entry.corp_name.toLowerCase().replace(/\s/g, ""),
        qLower
      );
      if (dist <= 2) {
        fuzzyResults.push({ entry, dist });
      }
    }
    fuzzyResults.sort((a, b) => a.dist - b.dist);
    if (fuzzyResults.length > 0) {
      return fuzzyResults.slice(0, limit).map((r) => r.entry);
    }
  }

  return [];
}

function sortByListed(entries: CorpCodeEntry[]): CorpCodeEntry[] {
  return entries.sort((a, b) => {
    const aListed = a.stock_code ? 0 : 1;
    const bListed = b.stock_code ? 0 : 1;
    return aListed - bListed;
  });
}

/**
 * Resolve corp_codes to names. Multi-company endpoints return codes only, so
 * without this a comparison table can't say which row is which company.
 */
export function getCorpNames(corpCodes: string[]): Record<string, string> {
  const c = initCache();
  const out: Record<string, string> = {};
  for (const code of corpCodes) {
    const entry = c.byCorpCode.get(String(code).padStart(8, "0"));
    if (entry) out[code] = entry.corp_name;
  }
  return out;
}

export async function getCorpCodeByName(
  name: string,
  apiKey?: string
): Promise<CorpCodeEntry | null> {
  const results = await searchCompanies(name, apiKey, 1);
  return results[0] || null;
}
